### ISSUE TITLE
[Feature]: SearchScreen 검색 기능

### ISSUE THREAD

**Issue by comye1** [gdsc-seoultech/CheggPrep_Clone#1]
## 기능 설명
- Firebase RDB에서 "all/decks" 아래의 모든 Deck를 불러오고 queryString으로 검색한 결과를 보여준다.

## Tasks
- [x] getAllDecks() - 리스너 부착 or 한 번씩 get으로 불러오기
- [x] getAllDecks() - 호출 위치
- [x] queryResult 함수 or val로 선언 후 get에서 필터링
- [x] SearchScreen 내 로직 수정
