### ISSUE TITLE
[Feature]: Deck 삭제 기능

### ISSUE THREAD

**Issue by comye1** [gdsc-seoultech/CheggPrep_Clone#2]
## 기능 설명
- 사용자가 자신이 생성한 Deck를 삭제한다.
- 다른 사용자가 그 Deck를 북마크에 추가한 경우를 고려해야 한다. 
- 메뉴에서 Delete 클릭 시 Dialog를 띄워 "Delete"가 클릭되면 삭제한다.

## Tasks
- [x] DeckViewModel - 삭제 함수 구현
- [x] DeckScreen - 메뉴에 연결하기
- [x] 삭제된 북마크 처리 - 다음 이슈로 #5 
- [x] Dialog 처리

**Comment by comye1** [comment]
![Screenshot_20220213-012601.png](https://user-images.githubusercontent.com/50735594/153719468-85b659ba-40d5-4d07-bf9b-d03f9db769a3.png)
![Screenshot_20220213-012608.png](https://user-images.githubusercontent.com/50735594/153719472-2aa57dbc-108e-4a20-9884-8a131492691a.png)
![Screenshot_20220213-012618.png](https://user-images.githubusercontent.com/50735594/153719473-5ef6eb61-85fe-4c64-aa7f-d8f56591dcfb.png)
